apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managedclusterset-clusterrole
rules:
  - apiGroups: ["cluster.open-cluster-management.io"]
    resources: ["managedclustersets/join"]
    resourceNames: ["dev","prod"]
    verbs: ["create"]
